language: objective-c
xcode_project: Momentus.xcodeproj
xcode_scheme: Momentus
osx_image: xcode9.1
xcode_sdk: iphonesimulator11.1

cache:
    directories:
    - Carthage

before_install:
    - brew update
    - brew outdated carthage || brew upgrade carthage
    - carthage bootstrap --no-use-binaries --platform iOS --cache-builds

