language: objective-c
xcode_project: Momentus.xcodeproj
xcode_scheme: Momentus

cache:
    directories:
    - Carthage

before_install:
    - brew update
    - brew outdated carthage || brew upgrade carthage
    - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

